package br.com.matteus.parkingmanagement.constant;

import lombok.Getter;

@Getter
public enum VehicleModel {

    COROLLA("Corolla"),
    HILUX("Hilux"),
    ETIOS("Etios"),
    YARIS("Yaris"),
    PRIUS("Prius"),
    CAMRY("Camry"),
    RAV4("RAV4"),
    SW4("SW4"),
    LANDCRUISER("Land Cruiser"),
    UNO("Uno"),
    MOBI("Mobi"),
    ARGO("Argo"),
    CRONOS("Cronos"),
    SIENA("Siena"),
    PALIO("Palio"),
    WEEKEND("Weekend"),
    STRADA("Strada"),
    TORO("Toro"),
    FIORINO("Fiorino"),
    DUCATO("Ducato"),
    KA("Ka"),
    FIESTA("Fiesta"),
    FOCUS("Focus"),
    ECOSPORT("EcoSport"),
    RANGER("Ranger"),
    FUSION("Fusion"),
    EDGE("Edge"),
    MUSTANG("Mustang"),
    F150("F-150"),
    F250("F-250"),
    F350("F-350"),
    F4000("F-4000"),
    FUSCA("Fusca"),
    GOL("Gol"),
    VOYAGE("Voyage"),
    SAVEIRO("Saveiro"),
    FOX("Fox"),
    POLO("Polo"),
    JETTA("Jetta"),
    TIGUAN("Tiguan"),
    AMAROK("Amarok"),
    GOLF("Golf"),
    UP("Up"),
    CROSSFOX("CrossFox"),
    SPACEFOX("SpaceFox"),
    PARATI("Parati"),
    KOMBI("Kombi"),
    BRASILIA("Brasília"),
    PASSAT("Passat"),
    VARIANT("Variant"),
    QUANTUM("Quantum"),
    SANTANA("Santana"),
    FAN("Fan"),
    BIZ("Biz"),
    CG("CG"),
    POP("Pop"),
    BROS("Bros"),
    CB300("CB 300"),
    XRE300("XRE 300"),
    PCX("PCX"),
    NXR160("NXR 160"),
    CB500("CB 500"),
    CB650("CB 650"),
    CB1000("CB 1000"),
    CBR1000("CBR 1000"),
    CBR600("CBR 600"),
    CBR500("CBR 500"),
    CBR650("CBR 650"),
    CBR250("CBR 250"),
    SHADOW("Shadow"),
    VISION("Vision"),
    CITY("City"),
    CIVIC("Civic"),
    CRV("CR-V"),
    FIT("Fit"),
    HRV("HR-V"),
    WRV("WR-V"),
    ACCORD("Accord"),
    SPEED("Speed");

    private final String displayName;

    VehicleModel(String displayName) {
        this.displayName = displayName;
    }
}
